project_id = "gvtsbnivuysunnjrpndk"

[functions.submit-order]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.send-welcome-newsletter]
verify_jwt = false

[functions.send-weekly-menu]
verify_jwt = false

[functions.generate-food-image]
verify_jwt = false
