project_id = "gvtsbnivuysunnjrpndk"

[functions.submit-order]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.send-welcome-newsletter]
verify_jwt = false

[functions.send-weekly-menu]
verify_jwt = false

[functions.generate-food-image]
verify_jwt = false

[functions.send-daily-report]
verify_jwt = false

[functions.extract-invoice-data]
verify_jwt = false

[functions.send-monthly-report]
verify_jwt = false

[functions.process-recurring-invoices]
verify_jwt = false

[functions.weather-forecast]
verify_jwt = false

[functions.send-rating-request]
verify_jwt = false

[functions.register-push]
verify_jwt = false
